development: &defaults
  adapter: postgresql
  encoding: unicode
  database: beer_dispenser_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *defaults
  database: beer_dispenser_test

production:
  <<: *defaults
  database: beer_dispenser_production